/**
 * /api/inquiry
 * Minimal production-safe inquiry endpoint for Vercel serverless.
 * - Validates required fields
 * - Honeypot support ("company")
 * - Logs to console always
 * - Optional outbound email via Resend (recommended) using env vars
 *
 * ENV (optional):
 * - RESEND_API_KEY
 * - OWNER_NOTIFY_EMAILS (comma-separated)  e.g. "cheeksbandg@gmail.com,owner2@gmail.com"
 * - FROM_EMAIL (must be verified in Resend) e.g. "Cheeks <noreply@yourdomain.com>"
 */

import { bad, requiredStr, safeNum, htmlEscape, sendResendEmail } from './lib/utils.js';

/**
 * Check if string looks like a valid email address
 * @param {string} s - String to check
 * @returns {boolean} True if string looks like email
 */
function looksLikeEmail(s) {
  // lightweight sanity check (server-side validation still keeps delivery optional)
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(s || '').trim());
}

/**
 * Validate date string format (YYYY-MM-DD)
 * @param {string} dateStr - Date string to validate
 * @returns {boolean} True if valid date format
 */
function isValidDate(dateStr) {
  if (!dateStr || typeof dateStr !== 'string') return false;
  // Check format YYYY-MM-DD
  if (!/^\d{4}-\d{2}-\d{2}$/.test(dateStr)) return false;
  // Use UTC to ensure consistent validation regardless of server timezone
  const d = new Date(dateStr + 'T00:00:00Z');
  return d instanceof Date && !isNaN(d) && d.toISOString().startsWith(dateStr);
}

/**
 * Check if date is in the future (UTC)
 * @param {string} dateStr - Date string to check
 * @returns {boolean} True if date is today or future
 */
function isFutureDate(dateStr) {
  if (!isValidDate(dateStr)) return false;
  // Both client and server use UTC for consistent validation.
  // This prevents mismatches where client accepts but server rejects the same date.
  const selected = new Date(dateStr + 'T00:00:00Z');
  const now = new Date();
  // Get today's date in UTC as YYYY-MM-DD string, then parse as UTC midnight
  const todayStr = now.toISOString().split('T')[0];
  const todayUTC = new Date(todayStr + 'T00:00:00Z');
  // Require selected date to be >= today in UTC
  return selected >= todayUTC;
}

/**
 * Validate time string format (HH:MM or HH:MM AM/PM)
 * @param {string} timeStr - Time string to validate
 * @returns {boolean} True if valid time format
 */
function isValidTime(timeStr) {
  if (!timeStr || typeof timeStr !== 'string') return false;
  const trimmed = timeStr.trim();
  // Accept HTML5 time input format (HH:MM) - 24-hour format: 00:00 to 23:59
  // Also accept 12-hour format with AM/PM for user convenience
  return /^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$/.test(trimmed) || 
         /^(0?[1-9]|1[0-2]):[0-5][0-9]\s?(AM|PM)$/i.test(trimmed);
}

/**
 * Build HTML email body for inquiry notification
 * @param {Object} payload - Inquiry payload object
 * @param {string} payload.name - Customer name
 * @param {string} payload.phone - Customer phone
 * @param {string} payload.email - Customer email
 * @param {string} payload.eventType - Event type
 * @param {string} payload.eventDate - Event date
 * @param {string} payload.eventTime - Event time
 * @param {number} payload.guests - Number of guests
 * @param {string} payload.package - Package selection
 * @param {string} payload.notes - Additional notes
 * @param {string} payload.src - Source tracking
 * @param {string} payload.pageUrl - Page URL
 * @returns {string} HTML email body
 */
function buildEmailHtml(payload) {
  const rows = [
    ['Name', payload.name],
    ['Phone', payload.phone],
    ['Email', payload.email],
    ['Event Type', payload.eventType],
    ['Date', payload.eventDate],
    ['Start Time', payload.eventTime],
    ['Guests', String(payload.guests)],
    ['Package', payload.package],
    ['Notes', payload.notes || ''],
    ['Source', payload.src || 'direct'],
    ['Page URL', payload.pageUrl || ''],
  ];

  const trs = rows.map(([k,v]) =>
    `<tr><td style="padding:8px 10px;border:1px solid #e5e7eb;font-weight:700;white-space:nowrap">${htmlEscape(k)}</td>`+
    `<td style="padding:8px 10px;border:1px solid #e5e7eb">${htmlEscape(v || '')}</td></tr>`
  ).join('');

  return `<!doctype html><html><body style="font-family:Arial,Helvetica,sans-serif;color:#111">
    <h2 style="margin:0 0 10px">New Event Inquiry — Cheeks</h2>
    <p style="margin:0 0 12px">Status: <strong>NEW</strong> (not booked until deposit is paid)</p>
    <table style="border-collapse:collapse;border:1px solid #e5e7eb">${trs}</table>
    <p style="margin:12px 0 0;font-size:12px;color:#6b7280">Generated by cheeks landing page funnel.</p>
  </body></html>`;
}


/**
 * Vercel serverless function handler for event inquiries
 * @param {Object} req - Request object
 * @param {Object} res - Response object
 * @returns {Promise<void>}
 */
export default async function handler(req, res) {
  try {
    if (req.method !== 'POST') {
      res.setHeader('Allow', 'POST');
      return bad(res, 405, 'Method not allowed');
    }
    
    // Set security headers
    res.setHeader('X-Content-Type-Options', 'nosniff');
    res.setHeader('Content-Type', 'application/json; charset=utf-8');

    const b = req.body || {};

    // Honeypot - silently ignore bot submissions
    if (typeof b.company === 'string' && b.company.trim().length > 0) {
      // Log honeypot hits for monitoring (but don't expose this to client)
      // eslint-disable-next-line no-console
      console.log('CHEEKS_HONEYPOT', { ip: (req.headers['x-forwarded-for'] || '').toString().split(',')[0].trim() || 'unknown' });
      return res.status(200).json({ ok: true, id: 'hp', status: 'ignored' });
    }

    const name = requiredStr(b.name, 80);
    const phone = requiredStr(b.phone, 40);
    const email = requiredStr(b.email, 120);
    const eventType = requiredStr(b.eventType, 60);
    const eventDate = requiredStr(b.eventDate, 20);
    const eventTime = requiredStr(b.eventTime, 20);
    const pkg = requiredStr(b.package, 2);
    const guests = safeNum(b.guests, 1, 200);
    const notes = requiredStr(b.notes || '', 1200);
    const q = req.query || {};
    const src = requiredStr((b.src || q.src || q.utm_source || q.utm_campaign || ''), 80);
    const pageUrl = requiredStr(b.pageUrl || '', 400);

    if (!name || !phone || !email || !eventType || !eventDate || !eventTime || !pkg || guests === null) {
      return bad(res, 400, 'Missing required fields');
    }
    if (!looksLikeEmail(email)) {
      return bad(res, 400, 'Invalid email format');
    }
    if (!isValidDate(eventDate)) {
      return bad(res, 400, 'Invalid date format. Expected YYYY-MM-DD');
    }
    if (!isFutureDate(eventDate)) {
      return bad(res, 400, 'Event date cannot be in the past');
    }
    if (!isValidTime(eventTime)) {
      return bad(res, 400, 'Invalid time format');
    }

    // Generate unique ID with timestamp and random component
    const id = `inq_${Date.now()}_${Math.random().toString(16).slice(2, 10)}`;

    const payload = {
      id,
      ts: new Date().toISOString(),
      name,
      phone,
      email,
      eventType,
      eventDate,
      eventTime,
      package: pkg,
      guests,
      notes,
      src: src || 'direct',
      pageUrl,
      ip: (req.headers['x-forwarded-for'] || req.headers['x-real-ip'] || '').toString().split(',')[0].trim() || 'unknown',
      ua: (req.headers['user-agent'] || '').toString().slice(0, 200) || 'unknown',
      status: 'NEW'
    };

    // Always log (so even without integrations, you have server logs in Vercel)
    // eslint-disable-next-line no-console
    console.log('CHEEKS_INQUIRY', JSON.stringify(payload));

    // Optional: notify owners via Resend
    const ownerList = (process.env.OWNER_NOTIFY_EMAILS || 'cheeksbandg@gmail.com')
      .split(',').map(s => s.trim()).filter(Boolean);
    const from = process.env.FROM_EMAIL || 'Cheeks Events <noreply@cheeksbar.com>';

    const html = buildEmailHtml(payload);

    let emailResult = { sent: false, reason: 'email not configured' };
    try {
      // Sanitize subject line to prevent email header injection
      const safeSubject = `New Event Inquiry (${guests} guests) — ${eventDate} ${eventTime}`.replace(/[\r\n]/g, ' ');
      emailResult = await sendResendEmail({
        to: ownerList,
        from,
        subject: safeSubject,
        html,
        replyTo: email
      });
    } catch (e) {
      emailResult = { sent: false, reason: String(e && e.message ? e.message : e) };
      // eslint-disable-next-line no-console
      console.error('CHEEKS_EMAIL_ERR', { error: String(e), inquiryId: id });
    }

    // Optional: customer confirmation (off by default)
    let customerResult = { sent: false, reason: 'disabled' };
    if (process.env.CUSTOMER_CONFIRM === '1') {
      const customerHtml = `<!doctype html><html><body style="font-family:Arial,Helvetica,sans-serif;color:#111">
        <h2 style="margin:0 0 10px">We got your request — Cheeks Bar & Grill</h2>
        <p style="margin:0 0 10px">Reference ID: <strong>${htmlEscape(id)}</strong></p>
        <p style="margin:0 0 10px">We’ll reach out soon to confirm details. Not booked until deposit is paid.</p>
        <p style="margin:0 0 10px;font-size:12px;color:#6b7280">If you need to finalize quickly, call (715) 393-4026.</p>
      </body></html>`;
      try {
        customerResult = await sendResendEmail({
          to: [email],
          from,
          subject: `Cheeks Event Request Received — ${eventDate}`,
          html: customerHtml,
          replyTo: ownerList[0] || undefined
        });
      } catch (e) {
        customerResult = { sent: false, reason: String(e && e.message ? e.message : e) };
      }
    }

    const receivedAt = new Date().toISOString();
    const response = {
      ok: true,
      id,
      receivedAt,
      status: 'NEW',

      data: {
        name,
        phone,
        email,
        eventType,
        eventDate,
        eventTime,
        guests,
        package: pkg,
        notes,
        src
      },
      bookedDefinition: 'BOOKED = deposit paid',
      ownerEmail: emailResult.sent ? 'sent' : 'not_sent',
      customerEmail: customerResult.sent ? 'sent' : 'not_sent'
    };
    res.status(200).json(response);
  } catch (err) {
    // eslint-disable-next-line no-console
    console.error('CHEEKS_INQUIRY_ERR', err);
    return bad(res, 500, 'Server error');
  }
}
