/**
 * /api/mark-booked
 * Marks an inquiry as BOOKED (deposit paid) and emits a BOH-friendly Event Sheet email.
 *
 * This endpoint is for internal use (Cody/owners). Protect it with ADMIN_TOKEN.
 *
 * ENV:
 * - ADMIN_TOKEN (required)
 * - RESEND_API_KEY (optional)
 * - OWNER_NOTIFY_EMAILS (optional)
 * - FROM_EMAIL (optional)
 */

function bad(res, code, msg) {
  res.status(code).json({ ok: false, error: msg });
  // Log error for monitoring
  if (code >= 500) {
    console.error('CHEEKS_BOOKED_API_ERROR', { code, msg, ts: new Date().toISOString() });
  }
}

function requiredStr(v, maxLen) {
  if (typeof v !== 'string') return '';
  const s = v.trim();
  if (!s) return '';
  return s.slice(0, maxLen);
}

function htmlEscape(s) {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

async function sendResendEmail({ to, from, subject, html }) {
  const apiKey = process.env.RESEND_API_KEY;
  if (!apiKey) return { sent: false, reason: 'RESEND_API_KEY not set' };

  const r = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: {
      'authorization': `Bearer ${apiKey}`,
      'content-type': 'application/json'
    },
    body: JSON.stringify({ from, to, subject, html })
  });

  const text = await r.text();
  if (!r.ok) return { sent: false, reason: `Resend error ${r.status}: ${text.slice(0, 300)}` };
  return { sent: true, raw: text };
}

function eventSheetHtml(payload) {
  const lines = [
    ['Status', 'BOOKED (deposit paid)'],
    ['Event', payload.eventType],
    ['Date', payload.eventDate],
    ['Start Time', payload.eventTime],
    ['Guests', payload.guests],
    ['Package', payload.package],
    ['Deposit', payload.deposit || '—'],
    ['Minimum Spend', payload.minimumSpend || '—'],
    ['Customer', `${payload.name} | ${payload.phone} | ${payload.email}`],
    ['Notes', payload.notes || '—'],
    ['Source', payload.src || 'direct'],
  ];

  const trs = lines.map(([k,v]) =>
    `<tr><td style="padding:8px 10px;border:1px solid #e5e7eb;font-weight:700;white-space:nowrap">${htmlEscape(k)}</td>`+
    `<td style="padding:8px 10px;border:1px solid #e5e7eb">${htmlEscape(v || '')}</td></tr>`
  ).join('');

  return `<!doctype html><html><body style="font-family:Arial,Helvetica,sans-serif;color:#111">
    <h2 style="margin:0 0 10px">BOH Event Sheet — Cheeks</h2>
    <p style="margin:0 0 12px">This sheet is designed to minimize BOH surprises. If anything changes, update the customer and re-issue a new sheet.</p>
    <table style="border-collapse:collapse;border:1px solid #e5e7eb">${trs}</table>
    <p style="margin:12px 0 0;font-size:12px;color:#6b7280">Generated by cheeks landing page funnel.</p>
  </body></html>`;
}

export default async function handler(req, res) {
  try {
    if (req.method !== 'POST') {
      res.setHeader('Allow', 'POST');
      return bad(res, 405, 'Method not allowed');
    }
    
    // Set security headers
    res.setHeader('X-Content-Type-Options', 'nosniff');
    res.setHeader('Content-Type', 'application/json; charset=utf-8');

    // Security: Validate admin token
    const token = (req.headers['x-admin-token'] || '').toString().trim();
    const expected = process.env.ADMIN_TOKEN;
    if (!expected) return bad(res, 500, 'ADMIN_TOKEN not set');
    // Use constant-time comparison to prevent timing attacks
    if (token.length !== expected.length || token !== expected) {
      return bad(res, 401, 'Unauthorized');
    }

    const b = req.body || {};
    const id = requiredStr(b.id, 80);
    if (!id) return bad(res, 400, 'Missing id');

    // The payload below can be pasted from Vercel logs (CHEEKS_INQUIRY JSON),
    // or you can pass fields again here. This keeps the flow lightweight for now.
    const payload = {
      id,
      name: requiredStr(b.name || '', 80),
      phone: requiredStr(b.phone || '', 40),
      email: requiredStr(b.email || '', 120),
      eventType: requiredStr(b.eventType || '', 60),
      eventDate: requiredStr(b.eventDate || '', 20),
      eventTime: requiredStr(b.eventTime || '', 20),
      guests: requiredStr(String(b.guests || ''), 12),
      package: requiredStr(b.package || '', 4),
      notes: requiredStr(b.notes || '', 1200),
      src: requiredStr(b.src || '', 80),
      deposit: requiredStr(b.deposit || '', 40),
      minimumSpend: requiredStr(b.minimumSpend || '', 40),
    };

    console.log('CHEEKS_BOOKED', JSON.stringify({ ...payload, ts: new Date().toISOString(), status: 'BOOKED' }));

    const ownerList = (process.env.OWNER_NOTIFY_EMAILS || 'cheeksbandg@gmail.com')
      .split(',').map(s => s.trim()).filter(Boolean);
    const from = process.env.FROM_EMAIL || 'Cheeks Events <noreply@cheeksbar.com>';

    const html = eventSheetHtml(payload);

    // Preview mode: return the Event Sheet HTML without sending email (useful for demos)
    if (b.preview === true) {
      return res.status(200).json({ ok: true, id, status: 'PREVIEW', previewHtml: html });
    }

    let emailResult = { sent: false, reason: 'email not configured' };
    try {
      emailResult = await sendResendEmail({
        to: ownerList,
        from,
        subject: `BOOKED: ${payload.eventType} — ${payload.eventDate} ${payload.eventTime} (${payload.guests} guests)`.replace(/[\r\n]/g, ' '),
        html
      });
    } catch (e) {
      emailResult = { sent: false, reason: String(e && e.message ? e.message : e) };
    }

    return res.status(200).json({ ok: true, id, status: 'BOOKED', email: emailResult.sent ? 'sent' : 'not_sent' });
  } catch (err) {
    console.error('CHEEKS_BOOKED_ERR', err);
    return bad(res, 500, 'Server error');
  }
}
